#!/bin/sh
# elvis: ddg            -- search duckduckgo
# henrycase@hush.com 20110104
. surfraw || exit 1

w3_config_hook () {
    def     SURFRAW_ddg_results         "$SURFRAW_results"
    def     SURFRAW_ddg_base_url        "http://www.duckduckgo.com"
    def     SURFRAW_ddg_search          search
    def     SURFRAW_ddg_params          ""
    defyn   SURFRAW_ddg_https_arg       0
    defyn   SURFRAW_ddg_safe_arg        0
    defyn   SURFRAW_ddg_redirect_arg    0
    defyn   SURFRAW_ddg_use_javascript  0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using DuckDuckGo (www.duckduckgo.com)
Local options:
    -d,-redirect                use redirection
    -j,-javascript              use javascript
    -s,-secure                  use the SSL search
    -p,-safe                    enable safe search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -s|-sec*)           setoptyn    SURFRAW_ddg_https_arg       1 ;;
    -p|-safe*)		setoptyn    SURFRAW_ddg_safe_arg        1 ;;
    -d|-redirect*)      setoptyn    SURFRAW_ddg_redirect_arg    1 ;;
    -j|-javascript*)    setoptyn    SURFRAW_ddg_use_javascript  1 ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
    
if ifyes $SURFRAW_ddg_https_arg ; then 
    SURFRAW_ddg_base_url="https://www.duckduckgo.com"
fi

echo "base url (pre-js): ${SURFRAW_ddg_base_url}"
# need to send the user to the non-javascript version if using a non-graphical
# browser
if ifno $SURFRAW_ddg_use_javascript ; then
    SURFRAW_ddg_base_url="${SURFRAW_ddg_base_url}/html"
fi

echo "base url (post js): ${SURFRAW_ddg_base_url}"

if ifyes $SURFRAW_ddg_safe_arg ; then
    SURFRAW_ddg_params="${SURFRAW_ddg_params}&kp=1"
fi

if ifyes $SURFRAW_ddg_redirect_arg ; then
    SURFRAW_ddg_params="${SURFRAW_ddg_params}&kd=1"
fi

escaped_args=`w3_url_of_arg $w3_args`
echo "${SURFRAW_ddg_base_url}/q=?${escaped_args}${SURFRAW_ddg_params}"
#w3_browse_url "${SURFRAW_ddg_base_url}/q=?${escaped_args}${SURFRAW_ddg_params}"
