#!/bin/sh
# $Id$
# elvis: ddg        -- search duckduckgo
. surfraw || exit 1

w3_config_hook () {
    def     SURFRAW_ddg_results "$SURFRAW_results"
    def     SURFRAW_ddg_search search
    def     SURFRAW_ddg_params ""
    defyn   SURFRAW_ddg_secure_arg 0
    defyn   SURFRAW_ddg_safe_arg 0
    defyn   SURFRAW_ddg_redirect_arg 0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using DuckDuckGo (www.duckduckgo.com)
Local options:
    -d,-redirect                use redirection
    -s,-secure                  use the SSL search
    -p,-safe                    enable safe search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -s|-sec*)           setoptyn    SURFRAW_ddg_https_arg       1 ;;
    -p|-safe*)		setoptyn    SURFRAW_ddg_safe_arg        1 ;;
    -d|-redirect*)      setoptyn    SURFRAW_ddg_redirect_arg    1 ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -n "$SURFRAW_ddg_https" ; then
    $SURFRAW_ddg_base_url="https://www.duckduckgo.com"
else
    $SURFRAW_ddg_base_url="http://www.duckduckgo.com"
fi

escaped_args=`w3_url_of_arg $w3_args`
    else
        w3_browse_url "$SURFRAW_ddg_base_url/q=?${escaped_args}"
    fi
fi
