#!/bin/sh
# $Id$
# elvis: ddg        -- search duckduckgo
. surfraw || exit 1

w3_config_hook () {
    def   SURFRAW_ddg "$SURFRAW_results"
    def   SURFRAW_ddg search
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using Google (www.google.com)
Local options:
    -s,-secure                  use the SSL search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -s|-sec*)           setoptyn    SURFRAW_ddg_https;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -n "$SURFRAW_ddg_https" ; then
    $SURFRAW_ddg_base_url="https://www.duckduckgo.com"
else
    $SURFRAW_ddg_base_url="http://www.duckduckgo.com"
fi

escaped_args=`w3_url_of_arg $w3_args`
    else
        w3_browse_url "$SURFRAW_ddg_base_url/q=?${escaped_args}"
    fi
fi
