#!/bin/sh
# elvis: sx             -- search stackexchange.com for questions
# coder@kyleisom.net 20110107
. surfraw || exit 1

w3_config_hook () {
    def     SURFRAW_sx_results      "$SURFRAW_results"
    def     SURFRAW_sx_search       search
    defyn   SURFRAW_sx_q            0
    defyn   SURFRAW_sx_tag          0
    defyn   SURFRAW_sx_unanswered   0
    defyn   SURFRAW_sx_ask          0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search stackoverflow.com
Local options:
    -a,-ask             ask a question (requires javascript)
    -q,-questions       show all questions
    -t,-tag             display the tag associated with the search term
    -u,-unanswered      display unanswered questions
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -a*)            setoptyn    SURFRAW_sx_ask          1           ;;
    -q*)            setoptyn    SURFRAW_sx_q            1           ;;
    -t*)            setoptyn    SURFRAW_sx_tag          1           ;;
    -u*)            setoptyn    SURFRAW_sx_unanswered   1           ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

escaped_args=`w3_url_of_arg $w3_args`

if [ "$SURFRAW_sx_tag" = 1 ]; then
    search="questions/tagged/"
elif [ "$SURFRAW_sx_unanswered" = 1 ]; then
    search="unanswered"
    escaped_args=""
elif [ "$SURFRAW_sx_q" = 1 ]; then
    search="questions"
    excaped_args=""
elif [ "$SURFRAW_sx_ask" = 1 ]; then
    search="questions/ask"
    escaped_args=""
else
    search="search?q="
fi

echo "search: $search"
echo "sargs: $escaped_args"
url="http://stackoverflow.com/${search}${escaped_args}"
echo "url: $url"

echo "w3_browse_url $url"
w3_browse_url $url
